### ISSUE TITLE
Word synonym of itself

### ISSUE THREAD

**Issue by NotAProton** [horrifyingHorse/wurds#3]
![image](https://github.com/user-attachments/assets/8aeac73c-2e94-45f9-bde7-27d7aaa1e659)

**Comment by NotAProton** [comment]
update sar?

**Comment by horrifyingHorse** [comment]
![image](https://github.com/user-attachments/assets/aca0e389-8359-4516-968e-de58547fab55)
Will be fixed **_soon_**

**Comment by def3r** [comment]
> update sar?

Will be fixed **_soon_**
![image](https://github.com/user-attachments/assets/2adabcef-11a8-4487-ac9d-74619ef459f6)

**Comment by horrifyingHorse** [comment]
> ![image](https://private-user-images.githubusercontent.com/81463636/351148770-8aeac73c-2e94-45f9-bde7-27d7aaa1e659.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMzIyNjEsIm5iZiI6MTcyNTAzMTk2MSwicGF0aCI6Ii84MTQ2MzYzNi8zNTExNDg3NzAtOGFlYWM3M2MtMmU5NC00NWY5LWJkZTctMjdkN2FhYTFlNjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDE1MzI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4MTBlMmQ2NzdiOWFjNmFlNjljNzQzYzczYTg2ZGEyYzZmMTU5NWFmNmViNzEzYTcwMTJjMzRmNGIwNjY2ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bieoCY8dNVnq-CZYXtveMOV6nv_ddXl3W-nZ7xu-Yuk)

![image](https://github.com/user-attachments/assets/22bb2d80-031d-4779-9490-1bd0cce23c15)

It's **almost** done sar.

**Comment by def3r** [comment]
![image](https://github.com/user-attachments/assets/54ba1466-e5bc-4904-9954-4873bc68e2a4)

It's almost done sar.

**Comment by def3r** [comment]
No idea why [api response](https://api.dictionaryapi.dev/api/v2/entries/en/sitcom) include the sitcom word synonym of itself, when the [wiki](https://en.wiktionary.org/wiki/sitcom) doesn't. Anyways, fixed in [`c561cd2`](https://github.com/horrifyingHorse/wurds/commit/c561cd2dae3d0ae47e8732ca083ade8b7d0bd465)

**Comment by NotAProton** [comment]
Thank you sar :pray:
